In [1]:
import sqlite3
import pandas as pd

In [12]:
conn = sqlite3.connect('C:/Users/chiso/Downloads/accident_data_v1.0.0_2023.db')

cursor = conn.cursor()

# Execute the query to get the list of tables
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

# Fetch all results
tables = cursor.fetchall()

print("Tables in the database:",  tables)

Tables in the database: [('accident',), ('casualty',), ('vehicle',), ('lsoa',)]

In [29]:
conn = sqlite3.connect('C:/Users/chiso/Downloads/accident_data_v1.0.0_2023.db')

queries = ["SELECT * FROM accident WHERE accident_year = 2020 LIMIT 5", "SELECT * FROM vehicle WHERE accident_year = 2020 LIMIT 5", "SELECT * FROM casualty WHERE accident_year = 2020 LIMIT 5", "SELECT * FROM lsoa LIMIT 5" ]

acc_data = pd.read_sql_query(queries[0], conn)
veh_data = pd.read_sql_query(queries[1], conn)
cas_data = pd.read_sql_query(queries[2], conn)
lsoa_data = pd.read_sql_query(queries[3], conn)
# Display the DataFrame
print("accident data", acc_data, "\n\n")
print("vehicle data",veh_data, "\n\n")
print("casualities data",cas_data, "\n\n")
print("lsoa data",lsoa_data, "\n\n")
    
# Close the connection
conn.close()

accident data   accident_index  accident_year accident_reference  location_easting_osgr  \
0  2020010219808           2020          010219808               521389.0
1  2020010220496           2020          010220496               529337.0
2  2020010228005           2020          010228005               526432.0
3  2020010228006           2020          010228006               538676.0
4  2020010228011           2020          010228011               529324.0

   location_northing_osgr  longitude   latitude  police_force  \
0                175144.0  -0.254001  51.462262             1
1                176237.0  -0.139253  51.470327             1
2                182761.0  -0.178719  51.529614             1
3                184371.0  -0.001683  51.541210             1
4                181286.0  -0.137592  51.515704             1

   accident_severity  number_of_vehicles  ...  \
0                  3                   1  ...
1                  3                   1  ...
2                  3                   1  ...
3                  2                   1  ...
4                  3                   1  ...

   pedestrian_crossing_physical_facilities light_conditions  \
0                                        9                1
1                                        4                1
2                                        0                4
3                                        4                4
4                                        0                4

   weather_conditions road_surface_conditions  special_conditions_at_site  \
0                   9                       9                           0
1                   1                       1                           0
2                   1                       2                           0
3                   1                       1                           0
4                   1                       1                           0

  carriageway_hazards urban_or_rural_area  \
0                   0                   1
1                   0                   1
2                   0                   1
3                   0                   1
4                   0                   1

   did_police_officer_attend_scene_of_accident  trunk_road_flag  \
0                                            3                2
1                                            1                2
2                                            1                2
3                                            1                2
4                                            1                2

   lsoa_of_accident_location
0                  E01004576
1                  E01003034
2                  E01004726
3                  E01003617
4                  E01004763

[5 rows x 36 columns]


vehicle data    vehicle_index accident_index  accident_year accident_reference  \
0         681716  2020010219808           2020          010219808
1         681717  2020010220496           2020          010220496
2         681718  2020010228005           2020          010228005
3         681719  2020010228006           2020          010228006
4         681720  2020010228011           2020          010228011

   vehicle_reference  vehicle_type  towing_and_articulation  \
0                  1             9                        9
1                  1             9                        0
2                  1             9                        0
3                  1             8                        0
4                  1             9                        0

   vehicle_manoeuvre  vehicle_direction_from  vehicle_direction_to  ...  \
0                  5                       1                     5  ...
1                  4                       2                     6  ...
2                 18                      -1                    -1  ...
3                 18                       1                     5  ...
4                 18                       3                     7  ...

   journey_purpose_of_driver  sex_of_driver  age_of_driver  \
0                          6              2             32
1                          2              1             45
2                          6              3             -1
3                          1              1             44
4                          6              1             20

   age_band_of_driver  engine_capacity_cc  propulsion_code  age_of_vehicle  \
0                   6                1968                2               6
1                   7                1395                1               2
2                  -1                  -1               -1              -1
3                   7                1798                8               8
4                   4                2993                2               4

   generic_make_model  driver_imd_decile  driver_home_area_type
0             AUDI Q5                  4                      1
1             AUDI A1                  7                      1
2                  -1                 -1                     -1
3        TOYOTA PRIUS                  2                      1
4        BMW 4 SERIES                 -1                     -1

[5 rows x 28 columns]


casualities data    casualty_index accident_index  accident_year accident_reference  \
0          484748  2020010219808           2020          010219808
1          484749  2020010220496           2020          010220496
2          484750  2020010220496           2020          010220496
3          484751  2020010228005           2020          010228005
4          484752  2020010228006           2020          010228006

   vehicle_reference  casualty_reference  casualty_class  sex_of_casualty  \
0                  1                   1               3                1
1                  1                   1               3                2
2                  1                   2               3                2
3                  1                   1               3                1
4                  1                   1               3                1

   age_of_casualty  age_band_of_casualty  casualty_severity  \
0               31                     6                  3
1                2                     1                  3
2                4                     1                  3
3               23                     5                  3
4               47                     8                  2

   pedestrian_location  pedestrian_movement  car_passenger  \
0                    9                    5              0
1                    1                    1              0
2                    1                    1              0
3                    5                    9              0
4                    4                    1              0

   bus_or_coach_passenger  pedestrian_road_maintenance_worker  casualty_type  \
0                       0                                   0              0
1                       0                                   0              0
2                       0                                   0              0
3                       0                                   0              0
4                       0                                   0              0

   casualty_home_area_type  casualty_imd_decile
0                        1                    4
1                        1                    2
2                        1                    2
3                        1                    3
4                        1                    3


lsoa data    objectid   lsoa01cd             lsoa01nm            lsoa01nmw  \
0         1  E01000001  City of London 001A  City of London 001A
1         2  E01000002  City of London 001B  City of London 001B
2         3  E01000003  City of London 001C  City of London 001C
3         4  E01000004  City of London 001D  City of London 001D
4         5  E01000005  City of London 001E  City of London 001E

    shape__area  shape__length                              globalid
0  1.298652e+05    2635.772001  68cc6127-1008-4fbe-a16c-78fb089a7c43
1  2.284189e+05    2707.986202  937edbc3-c1bf-4d35-b274-b0a1480a7c09
2  5.905477e+04    1224.774479  2686dcaf-10b9-4736-92af-4788d4feaa69
3  2.544551e+06   10718.466240  3c493140-0b3f-4b9a-b358-22011dc5fb89
4  1.895782e+05    2275.809358  b569093d-788d-41be-816c-d6d7658b2311

In [30]:
acc_data

,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,...,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
0,2020010219808,2020,010219808,521389.0,175144.0,-0.254001,51.462262,1,3,1,...,9,1,9,9,0,0,1,3,2,E01004576
1,2020010220496,2020,010220496,529337.0,176237.0,-0.139253,51.470327,1,3,1,...,4,1,1,1,0,0,1,1,2,E01003034
2,2020010228005,2020,010228005,526432.0,182761.0,-0.178719,51.529614,1,3,1,...,0,4,1,2,0,0,1,1,2,E01004726
3,2020010228006,2020,010228006,538676.0,184371.0,-0.001683,51.541210,1,2,1,...,4,4,1,1,0,0,1,1,2,E01003617
4,2020010228011,2020,010228011,529324.0,181286.0,-0.137592,51.515704,1,3,1,...,0,4,1,1,0,0,1,1,2,E01004763

In [31]:
veh_data

,vehicle_index,accident_index,accident_year,accident_reference,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,...,journey_purpose_of_driver,sex_of_driver,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,driver_home_area_type
0,681716,2020010219808,2020,010219808,1,9,9,5,1,5,...,6,2,32,6,1968,2,6,AUDI Q5,4,1
1,681717,2020010220496,2020,010220496,1,9,0,4,2,6,...,2,1,45,7,1395,1,2,AUDI A1,7,1
2,681718,2020010228005,2020,010228005,1,9,0,18,-1,-1,...,6,3,-1,-1,-1,-1,-1,-1,-1,-1
3,681719,2020010228006,2020,010228006,1,8,0,18,1,5,...,1,1,44,7,1798,8,8,TOYOTA PRIUS,2,1
4,681720,2020010228011,2020,010228011,1,9,0,18,3,7,...,6,1,20,4,2993,2,4,BMW 4 SERIES,-1,-1

In [32]:
cas_data

,casualty_index,accident_index,accident_year,accident_reference,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_home_area_type,casualty_imd_decile
0,484748,2020010219808,2020,010219808,1,1,3,1,31,6,3,9,5,0,0,0,0,1,4
1,484749,2020010220496,2020,010220496,1,1,3,2,2,1,3,1,1,0,0,0,0,1,2
2,484750,2020010220496,2020,010220496,1,2,3,2,4,1,3,1,1,0,0,0,0,1,2
3,484751,2020010228005,2020,010228005,1,1,3,1,23,5,3,5,9,0,0,0,0,1,3
4,484752,2020010228006,2020,010228006,1,1,3,1,47,8,2,4,1,0,0,0,0,1,3

In [37]:
acc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 36 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   accident_index                               5 non-null      object
 1   accident_year                                5 non-null      int64
 2   accident_reference                           5 non-null      object
 3   location_easting_osgr                        5 non-null      float64
 4   location_northing_osgr                       5 non-null      float64
 5   longitude                                    5 non-null      float64
 6   latitude                                     5 non-null      float64
 7   police_force                                 5 non-null      int64
 8   accident_severity                            5 non-null      int64
 9   number_of_vehicles                           5 non-null      int64
 10  number_of_casualties                         5 non-null      int64
 11  date                                         5 non-null      object
 12  day_of_week                                  5 non-null      int64
 13  time                                         5 non-null      object
 14  local_authority_district                     5 non-null      int64
 15  local_authority_ons_district                 5 non-null      object
 16  local_authority_highway                      5 non-null      object
 17  first_road_class                             5 non-null      int64
 18  first_road_number                            5 non-null      int64
 19  road_type                                    5 non-null      int64
 20  speed_limit                                  5 non-null      int64
 21  junction_detail                              5 non-null      int64
 22  junction_control                             5 non-null      int64
 23  second_road_class                            5 non-null      int64
 24  second_road_number                           5 non-null      int64
 25  pedestrian_crossing_human_control            5 non-null      int64
 26  pedestrian_crossing_physical_facilities      5 non-null      int64
 27  light_conditions                             5 non-null      int64
 28  weather_conditions                           5 non-null      int64
 29  road_surface_conditions                      5 non-null      int64
 30  special_conditions_at_site                   5 non-null      int64
 31  carriageway_hazards                          5 non-null      int64
 32  urban_or_rural_area                          5 non-null      int64
 33  did_police_officer_attend_scene_of_accident  5 non-null      int64
 34  trunk_road_flag                              5 non-null      int64
 35  lsoa_of_accident_location                    5 non-null      object
dtypes: float64(4), int64(25), object(7)
memory usage: 1.5+ KB

In [43]:
acc_data.isnull().sum()

accident_index                                 0
accident_year                                  0
accident_reference                             0
location_easting_osgr                          0
location_northing_osgr                         0
longitude                                      0
latitude                                       0
police_force                                   0
accident_severity                              0
number_of_vehicles                             0
number_of_casualties                           0
date                                           0
day_of_week                                    0
time                                           0
local_authority_district                       0
local_authority_ons_district                   0
local_authority_highway                        0
first_road_class                               0
first_road_number                              0
road_type                                      0
speed_limit                                    0
junction_detail                                0
junction_control                               0
second_road_class                              0
second_road_number                             0
pedestrian_crossing_human_control              0
pedestrian_crossing_physical_facilities        0
light_conditions                               0
weather_conditions                             0
road_surface_conditions                        0
special_conditions_at_site                     0
carriageway_hazards                            0
urban_or_rural_area                            0
did_police_officer_attend_scene_of_accident    0
trunk_road_flag                                0
lsoa_of_accident_location                      0
dtype: int64

In [47]:
acc_data.duplicated().sum()

0

In [49]:
acc_data.describe()

,accident_year,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,number_of_casualties,day_of_week,...,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag
count,5.0,5.000000,5.000000,5.000000,5.000000,5.0,5.000000,5.0,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.00000,5.0,5.0,5.0,5.000000,5.0
mean,2020.0,529031.600000,179959.800000,-0.142250,51.503823,1.0,2.800000,1.0,1.400000,3.400000,...,1.800000,3.400000,2.800000,2.600000,2.80000,0.0,0.0,1.0,1.400000,2.0
std,0.0,6292.067887,4065.568312,0.091662,0.035544,0.0,0.447214,0.0,0.547723,0.894427,...,4.024922,3.714835,1.643168,3.577709,3.49285,0.0,0.0,0.0,0.894427,0.0
min,2020.0,521389.000000,175144.000000,-0.254001,51.462262,1.0,2.000000,1.0,1.000000,2.000000,...,0.000000,0.000000,1.000000,1.000000,1.00000,0.0,0.0,1.0,1.000000,2.0
25%,2020.0,526432.000000,176237.000000,-0.178719,51.470327,1.0,3.000000,1.0,1.000000,3.000000,...,0.000000,0.000000,1.000000,1.000000,1.00000,0.0,0.0,1.0,1.000000,2.0
50%,2020.0,529324.000000,181286.000000,-0.139253,51.515704,1.0,3.000000,1.0,1.000000,4.000000,...,0.000000,4.000000,4.000000,1.000000,1.00000,0.0,0.0,1.0,1.000000,2.0
75%,2020.0,529337.000000,182761.000000,-0.137592,51.529614,1.0,3.000000,1.0,2.000000,4.000000,...,0.000000,4.000000,4.000000,1.000000,2.00000,0.0,0.0,1.0,1.000000,2.0
max,2020.0,538676.000000,184371.000000,-0.001683,51.541210,1.0,3.000000,1.0,2.000000,4.000000,...,9.000000,9.000000,4.000000,9.000000,9.00000,0.0,0.0,1.0,3.000000,2.0

In [50]:
acc_data.nunique()

accident_index                                 5
accident_year                                  1
accident_reference                             5
location_easting_osgr                          5
location_northing_osgr                         5
longitude                                      5
latitude                                       5
police_force                                   1
accident_severity                              2
number_of_vehicles                             1
number_of_casualties                           2
date                                           3
day_of_week                                    3
time                                           5
local_authority_district                       4
local_authority_ons_district                   4
local_authority_highway                        4
first_road_class                               3
first_road_number                              4
road_type                                      1
speed_limit                                    2
junction_detail                                3
junction_control                               4
second_road_class                              3
second_road_number                             2
pedestrian_crossing_human_control              2
pedestrian_crossing_physical_facilities        3
light_conditions                               2
weather_conditions                             2
road_surface_conditions                        3
special_conditions_at_site                     1
carriageway_hazards                            1
urban_or_rural_area                            1
did_police_officer_attend_scene_of_accident    2
trunk_road_flag                                1
lsoa_of_accident_location                      5
dtype: int64